<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>">
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/bootstrap.min.css">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/bootstrap-dialog.min.css">
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/datepicker3.min.css">
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/jquery.pagedown-bootstrap.min.css">
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>alpha/css/alpha.min.css">
    <?= ($allowCSSOverrides ? '<link rel="stylesheet" href="'.$config->get('app.url').'config/css/overrides.css">' : '') ?>

    <script src="<?= $config->get('app.url') ?>alpha/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?= $config->get('app.url') ?>alpha/js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

    <script src="<?= $config->get('app.url') ?>alpha/js/vendor/bootstrap-datepicker.min.js"></script>