<ul id="adminmenu" class="potato-menu">
	<li><a href="<?= $config->get('sysURL') ?>">Home</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=ListBusinessObjects') ?>">Admin Home</a></li>
	<li><a href="#">Logs &raquo;</a>			
		<ul>
			<li><a href="<?= FrontController::generateSecureURL('act=ViewLog&logPath='.$config->get('sysLogFile')) ?>">System Log</a></li>
			<li><a href="<?= FrontController::generateSecureURL('act=ViewLog&logPath='.$config->get('sysRoot').'logs/search.log') ?>">Search Log</a></li>
			<li><a href="<?= FrontController::generateSecureURL('act=ViewLog&logPath='.$config->get('sysRoot').'logs/feeds.log') ?>">Feed Log</a></li>
			<li><a href="<?= FrontController::generateSecureURL('act=ViewLog&logPath='.$config->get('sysRoot').'logs/tasks.log') ?>">Cron Tasks Log</a></li>
		</ul>
	</li>
	<li><a href="<?= FrontController::generateSecureURL('act=GenSecureQueryStrings') ?>">Generate Secure URL</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=ViewMetrics') ?>">Software Metrics</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=CacheManager') ?>">Manage Cache</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=TagManager') ?>">Manage Tags</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=ListDEnums') ?>">Manage DEnums</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=ListSequences') ?>">Manage Sequences</a></li>
	<li><a href="<?= FrontController::generateSecureURL('act=ViewTestResults') ?>">Unit Tests</a></li>
</ul>