<nav class="navbar navbar-default" role="navigation">
	<ul id="adminmenu" class="nav navbar-nav">
		<li><a href="<?= $config->get('app.url') ?>">Home</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\ListActiveRecordsController') ?>">Admin Home</a></li>
		<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Logs<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\LogController&logPath='.$config->get('app.file.store.dir').'logs/'.$config->get('app.log.file')) ?>">System Log</a></li>
				<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\LogController&logPath='.$config->get('app.file.store.dir').'logs/search.log') ?>">Search Log</a></li>
				<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\LogController&logPath='.$config->get('app.file.store.dir').'logs/feeds.log') ?>">Feed Log</a></li>
				<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\LogController&logPath='.$config->get('app.file.store.dir').'logs/tasks.log') ?>">Cron Tasks Log</a></li>
			</ul>
		</li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\GenSecureQueryStringController') ?>">Generate Secure URL</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\MetricController') ?>">Code Metrics</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\CacheController') ?>">Cache</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\TagController') ?>">Tags</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\DEnumController') ?>">DEnums</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\SequenceController') ?>">Sequences</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\PhpinfoController') ?>">PHP Info</a></li>
		<li><a href="<?= Alpha\Controller\Front\FrontController::generateSecureURL('act=Alpha\Controller\LogoutController') ?>">Logout</a></li>
	</ul>
</nav>

<?php if ($passwordResetRequired) { ?>
<div class="alert alert-danger">You current admin password matches the value of app.install.password from the config file, please reset it to something different!</div>
<?php } ?>