document.getElementById('pageModal').querySelector('.modal-body p').textContent = '<?= $prompt ?>';
document.getElementById('pageModalOkayButton').addEventListener('click', function(){
    document.getElementById('<?= $formFieldId ?>').setAttribute('value', '<?= $formFieldValue ?>');
    document.getElementById('<?= $formId ?>').submit();
}, false);

var pageModal = new bootstrap.Modal(document.getElementById('pageModal'), {
  keyboard: false
});

pageModal.show();