    <footer>
        <p>&copy; <?= date('Y') ?></p>
    </footer>
    </div>

        <script src="<?= $config->get('app.url') ?>js/vendor/bootstrap.min.js"></script>

        <script src="<?= $config->get('app.url') ?>js/vendor/bootstrap-dialog.min.js"></script>

        <script src="<?= $config->get('app.url') ?>js/vendor/jquery.pagedown-bootstrap.combined.min.js"></script>

        <script src="<?= $config->get('app.url') ?>js/validation.min.js"></script>

    </body>
</html>