    <footer>
        <p>&copy; <?= date('Y') ?></p>
    </footer>
    </div>

        <script src="<?= $config->get('app.url') ?>/bootstrap/js/vendor/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>></script>

        <script src="<?= $config->get('app.url') ?>/js/validation.min.js"></script>

    </body>
</html>