<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="<?= $config->get('app.url') ?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <link rel="stylesheet" href="<?= $config->get('app.url') ?>/css/alpha.min.css">
    <?= (isset($allowCSSOverrides) && $allowCSSOverrides ? '<link rel="stylesheet" href="'.$config->get('app.url').'/css/overrides.css">' : '') ?>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?= $config->get('app.url') ?>/js/vendor/jquery-3.1.0.min.js"><\/script>')</script>

    <?= (isset($duringCallbackOutput) ? $duringCallbackOutput : '') ?>

</head>
<body<?= (isset($onloadEvent) && $onloadEvent != '' ? ' onload="'.$onloadEvent.'"' : '') ?>>

<div class="container">

<?= (isset($cmsCallbackOutput) ? $cmsCallbackOutput : '') ?>