<?php

require_once 'AlphaException.inc';

/**
 * The exception class for a failed attempt to create a database index or foreign key constraint
 * 
 * @package Alpha Core Exceptions
 * @author John Collins <john@design-ireland.net>
 * @copyright 2008 John Collins
 * @version $Id$
 * 
 */
class FailedIndexCreateException extends AlphaException {
	/**
	 * The constructor
	 *
	 * @param string $message	 
	 */
	public function __construct($message) {		
		parent::__construct($message);
	}
}

?>