    <footer>
        <p>&copy; <?= date('Y') ?></p>
    </footer>
    </div> <!-- /container -->        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?= $config->get('app.url') ?>alpha/js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

        <script src="<?= $config->get('app.url') ?>alpha/js/vendor/bootstrap.min.js"></script>

        <script src="<?= $config->get('app.url') ?>alpha/js/main.js"></script>

        <script src="<?= $config->get('app.url') ?>alpha/js/validation.js"></script>

    </body>
</html>