    <footer>
        <p>&copy; <?= date('Y') ?></p>
    </footer>
    </div>

        <script src="<?= $config->get('app.url') ?>alpha/js/vendor/bootstrap.min.js"></script>

        <script src="<?= $config->get('app.url') ?>alpha/js/vendor/bootstrap-dialog.js"></script>

        <script src="<?= $config->get('app.url') ?>alpha/js/main.js"></script>

        <script src="<?= $config->get('app.url') ?>alpha/js/validation.js"></script>

    </body>
</html>