<form action="<?= $formAction ?>" method="POST" accept-charset="UTF-8">
	<table class="list_view">
		<tr>
			<th><?= $title ?></th>
		</tr>
		<tr>
			<td><?= $description ?><br><br>
			Site Section: <em><?= $section ?></em>&nbsp;&nbsp;&nbsp;
			Date Added: <em><?= $dateAdded ?></em>
			</td>
		</tr>
		<tr>
			<td align="center">
			<?= $viewButton ?>
			<?= $adminButtons ?>
			</td>
		</tr>
		<?= $formSecurityFields ?>
	</table>
</form>