<form action="<?= $formAction ?>" id="<?= $formID ?>" method="POST" enctype="multipart/form-data">
	<table class="edit_view">	
		<?= $formFields ?>
		<tr><td colspan="2">
		<?= $saveButton ?>
		&nbsp;&nbsp;
		<?= $deleteButton ?>
		<?php if(isset($tagsButton)) { ?>
			&nbsp;&nbsp;
			<?= $tagsButton ?>
		<?php }?>
		&nbsp;&nbsp;
		<?= $cancelButton ?>
		</td></tr>
		<?= $fileAttachments; ?>
		<?= $formSecurityFields ?>	
	</table>
	<input type="hidden" name="version_num" value="<?= $version_num ?>"/>
</form>
<div id="helpPage"></div>